kind: pipeline
name: default

trigger:
  event:
    - push

steps:
  - name: 1
    image: node:10-alpine
    environment:
      env:
        from_secret: .env
    commands:
      - echo "$env" > .env
      - npm ci
      - npm test
      
  - name: bump
    image: xplugins/bump
    settings:
      github_token: 
        from_secret: github_token
      versionfile: VERSION
  # - name: build
  #   image: plugins/docker
  #   settings:
  #     repo: todo/todo
  #     username: xmorse
  #     # cache_from: xplugins/bump
  #     tags: 
  #       - latest
  #       # [bump]
  #       - 1.0.3
  #     password:
  #       from_secret: docker_password
  - name: npm
    image: plugins/npm
    commands:
      - npx tsc
    settings:
      username: xmorse
      password:
        from_secret: npm_password
      email: beats.by.morse@gmail.com


